### ISSUE TITLE
从浏览器输入地址后发生了什么

### ISSUE THREAD

**Issue by twinkle77** [twinkle77/Knowledge-sharing#12]
描述下整个过程

**Comment by sinner77** [comment]
DNS lookup（缓存）
发起请求 
	- 判断expire缓存，是否发起真实请求
	- 带上上次的 last-modified和etag。
	- 带上cookie
	- 带上诸多header，referrer，ua等
	- 是否支持gzip
请求到服务端
	- 判断last-modified和etag，无变化直接返回403
	- cdn 或者 应用服务器
	- slb负载均衡
	- nginx，转发，缓存策略等
	- 应用进程
	- response ,gzip
请求响应
	- 301 永久重定向，302 重定向
	- 4xx 请求错误
	- 5xx 应用内部错误
浏览器渲染
	- 解析dom
	- 请求css,js，图片资源。并行，有限制
	- 执行js，css会阻塞渲染和加载。

**Comment by cobish** [comment]
我觉得这一篇讲得也很直接了当，[链接](http://igoro.com/archive/what-really-happens-when-you-navigate-to-a-url/)。

**Comment by sinner77** [comment]
@cobish 哈哈。这篇好。我找个时间把它总结下来。我上面的回答并不好，一直想改，总觉得这个问题回答起来有点多（难记），才想等到面试前几天再总结。

**Comment by sinner77** [comment]
**从前端角度将“从浏览器输入地址后发生了什么？”**

个人觉得可以重点从http缓存策略，和浏览器解析流程来讲。
（答案不一，以下仅供参考）

1. 输入地址

2. 浏览器查找域名的 IP 地址(通过DNS将域名解析成ip地址)，DNS缓存查找过程为：
    1.  浏览器缓存
    2.  系统缓存
    3.  路由器缓存
    4.  ....

3. 客户端与服务器通过3次握手建立TCP连接

4. 浏览器向服务器发送一个 HTTP 请求（穿插http缓存策略）
    
5. 服务器处理请求

6. 服务器返回一个 HTTP 响应

7. 如果是http1.1以上版本，会保持长连接。如果是http1.0,会通过4次挥手断开连接。 

8. 浏览器解析HTML（穿插浏览器渲染流程）

9. 并行下载js、css、图片、视频、音频等资源。并行请求个数有限制

10. 解析执行css,js。浏览器reflow,repaint（穿插js,css的阻塞问题）

11. 页面构建完成

**Comment by sinner77** [comment]
@cobish 觉得说太少不好，说太多扯到关系的知识又太多。你说如何是好？

**Comment by cobish** [comment]
是啊，我也是这么觉得。只能是能记多少是多少啦～

**Comment by sinner77** [comment]
1. 输入url

2. 浏览器查找域名的 IP 地址,这个过程称为DNS解析。首先会先查找缓存，DNS缓存查找过程为：
    1.  浏览器缓存
    2.  系统缓存
    3.  互联网服务提供商（ISP）的DNS缓存
    4.  ....
    5.  一层一层向上查找最后返回ip地址

4. 客户端向服务器发送一个 HTTP 请求
    请求报文包含4个部分：请求行，请求头，空行，请求体
    请求报文携带一些至关重要的信息，如请求方法，协议版本，内容编码，cookie或者跟缓存相关的字段。

5. 接着，传输层TCP传输报文
    位于传输层的TCP协议为传输报文提供可靠的字节流服务。它为了方便传输，将大块的数据分割成以报文段为单位的数据包进行管理，并为它们编号，方便服务器接收时能准确地还原报文信息。TCP协议过“三次握手”等方法保证传输的安全可靠。
    
6. 数据到达网络层
    IP协议的作用是把TCP分割好的各种数据包传送给接收方。而要确保能传到接收方还需要接收方的MAC地址，也就是物理地址。这时，网络层ARP协议将ip地址解析成在数据链路层使用的物理地址。

7. 数据到达数据链路层
   在找到对方的MAC地址后，就将数据发送到数据链路层传输。这时，客户端发送请求的阶段结束。
 
8. 服务器接收到请求
    接收端的服务器在链路层接收到数据包，再层层向上直到应用层。这过程中包括在运输层通过TCP协议将分段的数据包重新组成原来的HTTP请求报文。
    
9. 服务器处理请求

10. 服务器返回一个 HTTP 响应
    响应报文包含4个部分：状态行，响应头，空行，响应体
    响应报文也携带一些至关重要的信息，如状态码，Set-Cookie字段或者跟缓存相关的字段。
    
11. 客户端受到响应。
    如果是http1.1以上版本，此时默认会保持长连接。如果是http1.0,会    通过4次挥手断开连接。

12. 浏览器解析HTML

13. 并行下载js、css、图片、视频、音频等资源。(并行请求个数有限制)
    1. 解析html以构建dom树，构建过程采用深度优先遍历，只有当前节点的所有子节点都构建好后才会去构建当前节点的下一个兄弟节点
    2. 解析css以构建css规则树
    3. 根据dom树和css规则树构建render树，render树的每个节点附带有相应的css属性。但render树 ！= dom树，像display:none 的东西就没有放在渲染树中了。
    4. 布局render树：确定树上每个节点在屏幕上的确切坐标
    5. 绘制render树：使用浏览器组成之一称为"UI后端层"绘制每个节点

14. 到此，页面构建完成
