### ISSUE TITLE
script标签的defer和async

### ISSUE THREAD

**Issue by twinkle77** [twinkle77/Knowledge-sharing#31]
defer和async的特点，区别，实践

**Comment by sinner77** [comment]
|--- | script标签放head里时 |
|---|---|
|没有defer和async| 浏览会立即加载并执行脚本，阻塞了后面的html解析|
|只有defer| 加载过程和html解析同步，但脚本的执行要在html解析完成之后，一般在document.DOMContentLoaded事件触发之前|
|只有async| 脚本的加载和执行与html解析并行执行 |
|defer和async都在| 跟‘只有async’情况一样，在async不支持的时候启用defer |


**defer和async相同点**： 

* 加载文件时不阻塞页面渲染
* 对于inline的script无效, 只对外部脚本文件有效

**defer和async不同点**： 

* defer并行下载，延迟执行，并且顺序执行
* async并行下载，立即执行，不按顺序执行

**实践**：

* 从实用角度来讲，首先把所有脚本都丢到 </body> 之前是最佳实践，因为对于旧浏览器来说这是唯一的优化选择，此法可保证非脚本的其他一切元素能够以最快的速度得到加载和解析。
* 从defer的角度来讲，在兼容性没问题的情况下，利用defer的异步加载，相比js放到底部什么都不加，节省了脚本文件的下载时间。
* 从async的角度来讲，对于那些可以**不依赖任何脚本或不依赖dom或者不被任何脚本依赖的脚本**来说是合适的，例子：百度分析

**参考资料**：
[script标签的defer和async](https://segmentfault.com/a/1190000006778717)

**Comment by cobish** [comment]
请问 ``async`` 的**立即执行**不会阻塞页面的渲染，是吗？

**Comment by sinner77** [comment]
是的。异步加载和执行。

**Comment by sinner77** [comment]
[链接，拉到下面，有个跟普通script标签的对比表](https://www.igvita.com/2014/05/20/script-injected-async-scripts-considered-harmful/)

**Comment by cobish** [comment]
好的，谢谢回复~
