### ISSUE TITLE
读《计算机网络》的笔记

### ISSUE THREAD

**Issue by twinkle77** [twinkle77/Knowledge-sharing#45]
* 计算机网络分层结构
* tcp/ip三次握手，四次挥手
* .....

**Comment by sinner77** [comment]
**计算机网络分层结构**

OSI/RM（Open Systems Interconnection Reference Model, 简称**OSI**）-开放系统互连基本参考模型

| OSI 7层模型 |
|--|
| 应用层 |
| 表示层 |
| 会话层 |
| 运输层 |
| 网络层 |
| 数据链路层 |
| 物理层 |


| TCP/IP 4层模型 |
|--|
| 应用层 |
| 运输层 |
| 网际层 |
| 网络接口层 |

**Comment by sinner77** [comment]
## 运输层知识点

**运输层的两个主要协议：**

1. 用户数据报协议UDP
2. 传输控制协议TCP


**UDP的特点**

1. 面向无连接
2. 尽最大努力交付，即不保证可靠交付，因此主机不需要维持复杂的链接状态表
3. UDP是面向报文的。应用层交给UDP多长的报文，UDP就照样发送，既不合并，也不拆分。一次交付一个完整的报文。
4. UDP没有拥塞控制。因此网络出现的拥塞不会使源主机的发送速率降低。
5. UDP支持一对一，一对多，多对一和多对多的交互通信。
6. UDP的首部开销小，只有8个字节，比TCP的20个字节的首部要短。


**TCP的特点**

1. 面向连接的运输层协议。在使用TCP协议之前，必须先建立TCP连接。在传送数据完毕后，必须释放已经建立的TCP连接。
2. 每一条TCP连接只能有两个端点，即每一条TCP连接只能是点对点的。
3. TCP提供可靠交付的服务。即通过TCP连接传送的数据，无差错，不丢失，不重复，并且按序到达。
4. TCP提供全双工通信。TCP允许通信双方的应用进程在任何时候都能发送数据。
5. TCP是面向字节流的。TCP把应用程序交下来的数据看成仅仅是一连串的无结构的字节流。

**TCP和UDP的区别**

TCP和UDP在发送报文时所采用的方式完全不同。TCP并不关心应用进程一次把多长的报文发送到TCP的缓存中，而是**根据对方给出的窗口值和当前网络拥塞的程度**来决定一个报文段应包含多少个字节。如果应用进程传送到TCP缓存的数据块太长，TCP就可以把它划分短一些再传送。


**TCP报文段组成**

一个TCP报文段分为首部和数据两部分，而TCP的全部功能都体现在它首部中各字段的作用。

重要字段：

序号：指的是本报文段所发送的数据的第一个字节的序号。（TCP是面向字节流的。在一个TCP连接中传送的字节流中的每一个字节都按顺序编号。整个要传送的字节流的起始序号必须在连接建立时设置）

确认号：期望收到对方下一个报文段的第一个数据字节的序号。

确认ACK：当ACK=1时确认号字段有效。当ACK=0确认号字段无效。

同步SYN：SYN置1标识这是一个连接请求或连接接受报文。

终止FIN：当FIN=1时，表示释放连接。

窗口：从本报文端首部中的确认号算起，明确指出了现在允许对方发送的数据量。窗口值是动态变化的。


**TCP可靠传输实现**

1. *滑动窗口协议*。TCP的滑动窗口是以字节为单位的。假定客户端A收到服务端B发来的确认报文段，其中窗口是20，而确认号是31,客户端A就是根据这两个数据来构造自己的发送窗口。窗口字段明确指出了现在允许对方发送的数据量，这让双方的数据传送无差错，不重复，并按序到达。
2. 凡是已经发送过的数据，在未收到确认之前都必须暂时保留，以便在*超时重传* 时使用。

**TCP流量控制实现**

流量控制就是让发送方的发送速率不要太快，要让接收方来得及接收。
TCP利用可变窗口实现流量控制，发送方的发送窗口不能超过接收方给出的接受窗口的数值。

**TCP拥塞控制**

拥塞控制就是防止过多的数据注入到网络中，使网络中的路由器或链路不致过载。

**TCP拥塞控制算法**

慢开始与拥塞避免：
发送方维持一个拥塞窗口的状态变量。拥塞窗口的大小取决于网络的拥塞程度，并且动态地在变化。发送方让自己的发送窗口等于拥塞窗口。
慢开始算法：由小到大逐渐增大拥塞窗口。通常在刚开始发送报文段时，先把拥塞窗口设置为一个最大报文段MSS的数值。使用慢开始算法后，每经过一个传输轮次，拥塞窗口就加倍。
拥塞避免算法：让拥塞窗口缓慢地增大，每经过一个往返时间RTT就把拥塞窗口加1，而不是加倍。

为了防止拥塞窗口CWND增长过大引起网络拥塞，还需要设置一个慢开始门限状态变量sshthresh。
CWND < sshthresh 使用慢开始算法
CWND > sshthresh 使用拥塞避免算法

 
快重传与快恢复：

快重传：要求接收方每收到一个失序的报文段后就立即发出重复确认，而不要等待自己发送数据时才进行捎带确认。
快恢复：当发送方连续收到3个重复确认时，把慢开始门限减半，把CWND值设置为慢开始门限减半后的数组，接下去执行拥塞避免算法。

**Comment by sinner77** [comment]
**3次握手**

第一次握手：
客户端向服务器发送连接请求报文段，这时首部中的**同步位SYN=1**，同时选择一个**初始序号seq=x**。TCP规定，SYN报文段（SYN=1时）不能携带数据，但要消耗一个序号。
这时客户端进入“同步已发送”状态

第二次握手：
服务器收到请求报文端后，如同意连接，则向客户端发出确认。
此时在确认报文段中把**SYN和ACK位都置1**，**确认号是ack=x+1**。
同时为自己选择一个**初始序号seq=y**。
这时服务器进入“同步收到”状态。

第三次握手：
客户端收到服务器的确认连接报文，还要给服务器确认。
确认报文段的**ACK置1**，**确认号ack=y+1**,而自己的序号**seq=x+1**。
这时客户端进入“已建立连接”状态

> TCP3次握手4个重要的位置： 同步标志位SYN,确认标志位ACK，确认号, 序号


**为什么客户端还要发送一次确认？（为什么要3次握手）**

防止**已失效的连接请求报文**段突然又传到服务器，因而产生错误。
假如客户端发送两个连接请求，第一个连接请求延误了，第二个连接请求正常到达并建立了连接。
如果延误的连接请求某个时刻到达服务器。
假定不采用3次握手，新的连接就建立了。
这就导致早应该失效的连接请求最后却确立了新的连接。

**Comment by sinner77** [comment]
**TCP4次挥手**

第一次挥手：
客户端向服务器发送**释放报文段**，
这时首部中的终止位FIN=1，同时选择一个初始序号seq=x。(前面已传送过的数据的最后一个字节的序号加1);
这时客户端进入“终止等待1”状态

第二次挥手：
服务器收到释放报文端后，向客户端发出确认。
此时在**确认报文段**中把ACK位都置1，确认号是ack=x+1，序号seq=y(前面已传送过的数据的最后一个字节的序号加1);
这时服务器进入“关闭等待”状态。

客户端收到服务器的确认后，进入“终止等待2”状态，等待服务器发出连接释放报文

第三次挥手：
服务器向客户端发送释放报文段，这时首部中的终止位FIN=1，同时选择一个初始序号seq=w。重复上次发送过的确认号ack=x+1。
这时服务器进入“最后确认”状态

第四次挥手：
客户端收到释放报文端后，向服务器发出确认。
此时在确认报文段中把ACK位都置1，确认号是ack=w+1，序号seq=x+1(前面已传送过的数据的最后一个字节的序号加1);
经过**时间等待计时器**设置的时间2MSL后，服务器进入“关闭”状态。

> TCP4次握手4个重要的位置： 终止标志位FIN,确认标志位ACK，确认号, 序号
